[package]
name = "instagen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.19.1"
tokio = { version = "1.36.0", features = ["full"] }
open = "5"